### ISSUE TITLE
Add subflow + layout example

### ISSUE THREAD

**Issue by fum4** [idootop/reactflow-auto-layout#3]
Hello,

I'm having a hard time implementing auto layouting in the context of subflows. From what I understand the demo app should be able to handle this, but I can't manage to make a working example.

This is my workflow structure (using `parentNode` as we are using reactflow@11):

```
{
  "nodes": [
    {
      "id": "A",
      "type": "base"
    },
    {
      "id": "B",
      "type": "base"
    },
    {
      "id": "C",
      "type": "base",
      "parentNode": "A",
      "extent": "parent"
    },
    {
      "id": "D",
      "type": "base",
      "parentNode": "A",
      "extent": "parent"
    },
    {
      "id": "E",
      "type": "base",
      "parentNode": "A",
      "extent": "parent"
    },
    {
      "id": "F",
      "type": "base"
    }
  ],
  "edges": [
    {
      "id": "A#B",
      "source": "A",
      "target": "B",
      "sourceHandle": "A#source",
      "targetHandle": "B#target"
    },
    {
      "id": "B#F",
      "source": "B",
      "target": "F",
      "sourceHandle": "B#source",
      "targetHandle": "F#target"
    },
    {
      "id": "C#D",
      "source": "C",
      "target": "D",
      "sourceHandle": "C#source",
      "targetHandle": "D#target"
    },
    {
      "id": "D#E",
      "source": "D",
      "target": "E",
      "sourceHandle": "D#source",
      "targetHandle": "E#target"
    }
  ]
}
```

This is what react flow renders. As you can see the 3 nodes that should be part of the subflow are not rendered inside the parent node:

<img width="540" alt="Screenshot 2024-11-11 at 15 24 50" src="https://github.com/user-attachments/assets/3632972c-7de3-4a01-952c-8c9bdcdefc5c">

I tried with all available layout algorithms and the results look similar. Not sure what I'm missing but I appreciate any help 🙏 

Thanks a lot!

P.S. I think this might be very useful as from what I see there are a lot of people having a hard time implementing this.

**Comment by idootop** [comment]
Based on the node and edge data you provided, the layout in your screenshot looks as expected. 

<img width="519" alt="图片" src="https://github.com/user-attachments/assets/b57b3335-50fc-4173-b2fb-0bf1997da37b">


It seems there might be some confusion regarding the concepts of subflows and groups.

I suggest posting your issue on the React Flow GitHub repository, as the functionality you're aiming for is unrelated to this project.
